// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PeluqueriaData.Models;

public partial class PeluqueriaDbContext : DbContext
{
    public PeluqueriaDbContext(DbContextOptions<PeluqueriaDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TDetalleTurno> TDetallesTurnos { get; set; }

    public virtual DbSet<TServicio> TServicios { get; set; }

    public virtual DbSet<TTurno> TTurnos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TDetalleTurno>(entity =>
        {
            entity.HasKey(e => new { e.IdServicio, e.IdTurno }).HasName("pk_detalle_turno");

            entity.ToTable("T_detalles_turno");

            entity.HasIndex(e => e.IdTurno, "IX_T_detalles_turno");

            entity.Property(e => e.IdServicio).HasColumnName("id_servicio");
            entity.Property(e => e.IdTurno).HasColumnName("id_turno");
            entity.Property(e => e.Observaciones)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("observaciones");

            entity.HasOne(d => d.IdServicioNavigation).WithMany(p => p.TDetallesTurnos)
                .HasForeignKey(d => d.IdServicio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_detalle_turno_servicio");

            entity.HasOne(d => d.IdTurnoNavigation).WithMany(p => p.TDetallesTurnos)
                .HasForeignKey(d => d.IdTurno)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_detalle_turno_turno");
        });

        modelBuilder.Entity<TServicio>(entity =>
        {
            entity.HasKey(e => e.IdServicio);

            entity.ToTable("T_servicios");

            entity.Property(e => e.IdServicio).HasColumnName("id_servicio");
            entity.Property(e => e.Costo).HasColumnName("costo");
            entity.Property(e => e.EnPromocion).HasColumnName("en_promocion");
            entity.Property(e => e.FechaBaja).HasColumnName("fecha_baja");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<TTurno>(entity =>
        {
            entity.HasKey(e => e.IdTurno);

            entity.ToTable("T_turnos");

            entity.Property(e => e.IdTurno).HasColumnName("id_turno");
            entity.Property(e => e.Cliente)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("cliente");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
            entity.Property(e => e.FechaBaja)
                .HasColumnType("datetime")
                .HasColumnName("fecha_baja");
            entity.Property(e => e.MotivoBaja)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("motivo_baja");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}