// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace PeluqueriaData.Models;

public partial class TServicio
{
    public int IdServicio { get; set; }

    public string Nombre { get; set; }

    public double Costo { get; set; }

    public bool EnPromocion { get; set; }

    public DateTime? FechaBaja { get; set; }

    public string MotivoBaja { get; set; }

    [JsonIgnore]
    public virtual ICollection<TDetalleTurno> TDetallesTurnos { get; set; } = new List<TDetalleTurno>();
}