// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PeluqueriaData.Models;

public partial class TTurno
{
    public int IdTurno { get; set; }

    public DateTime Fecha { get; set; }

    public string Cliente { get; set; }

    public DateTime? FechaBaja { get; set; }

    public string MotivoBaja { get; set; }

    public virtual ICollection<TDetalleTurno> TDetallesTurnos { get; set; } = new List<TDetalleTurno>();
}